### ISSUE TITLE
> d:\tf-faster-rcnn-windows\lib\layer_utils\proposal_target_layer.py(138)_sample_rois() -> keep_inds = np.append(fg_inds, bg_inds) (Pdb)

### ISSUE THREAD

**Issue by kmust-why** [lijianaiml/tf-faster-rcnn-windows#1]
image: D:\tf-faster-rcnn-windows\data\VOCdevkit2007\VOC2007\JPEGImages\class8_1.PNG
> d:\tf-faster-rcnn-windows\lib\layer_utils\proposal_target_layer.py(138)_sample_rois()
-> keep_inds = np.append(fg_inds, bg_inds)
(Pdb) c
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [0,44] vs. [128,44]
	 [[Node: gradients/LOSS_default/mul_9_grad/mul_1 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](vgg_16_1/rpn_rois/proposal_target:5, gradients/LOSS_default/Sum_1_grad/Tile)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/tf-faster-rcnn-windows/tools/trainval_net.py", line 143, in <module>
    max_iters=args.max_iters)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\model\train_val.py", line 377, in train_net
    sw.train_model(sess, max_iters)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\model\train_val.py", line 294, in train_model
    self.net.train_step(sess, blobs, train_op)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\nets\network.py", line 497, in train_step
    feed_dict=feed_dict)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [0,44] vs. [128,44]
	 [[Node: gradients/LOSS_default/mul_9_grad/mul_1 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](vgg_16_1/rpn_rois/proposal_target:5, gradients/LOSS_default/Sum_1_grad/Tile)]]

Caused by op 'gradients/LOSS_default/mul_9_grad/mul_1', defined at:
  File "D:/tf-faster-rcnn-windows/tools/trainval_net.py", line 143, in <module>
    max_iters=args.max_iters)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\model\train_val.py", line 377, in train_net
    sw.train_model(sess, max_iters)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\model\train_val.py", line 248, in train_model
    lr, train_op = self.construct_graph(sess)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\model\train_val.py", line 131, in construct_graph
    gvs = self.optimizer.compute_gradients(loss)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\optimizer.py", line 414, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 581, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 353, in _MaybeCompile
    return grad_fn()  # Exit early
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 581, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py", line 747, in _MulGrad
    array_ops.reshape(math_ops.reduce_sum(x * grad, ry), sy))
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 894, in binary_op_wrapper
    return func(x, y, name=name)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1117, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2725, in _mul
    "Mul", x=x, y=y, name=name)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'LOSS_default/mul_9', defined at:
  File "D:/tf-faster-rcnn-windows/tools/trainval_net.py", line 143, in <module>
    max_iters=args.max_iters)
[elided 1 identical lines from previous traceback]
  File "D:\tf-faster-rcnn-windows\tools\..\lib\model\train_val.py", line 248, in train_model
    lr, train_op = self.construct_graph(sess)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\model\train_val.py", line 123, in construct_graph
    anchor_ratios=cfg.ANCHOR_RATIOS)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\nets\network.py", line 434, in create_architecture
    self._add_losses()
  File "D:\tf-faster-rcnn-windows\tools\..\lib\nets\network.py", line 308, in _add_losses
    loss_box = self._smooth_l1_loss(bbox_pred, bbox_targets, bbox_inside_weights, bbox_outside_weights)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\nets\network.py", line 272, in _smooth_l1_loss
    out_loss_box = bbox_outside_weights * in_loss_box
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 894, in binary_op_wrapper
    return func(x, y, name=name)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1117, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2725, in _mul
    "Mul", x=x, y=y, name=name)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [0,44] vs. [128,44]
	 [[Node: gradients/LOSS_default/mul_9_grad/mul_1 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](vgg_16_1/rpn_rois/proposal_target:5, gradients/LOSS_default/Sum_1_grad/Tile)]]

Process finished with exit code 1

**Comment by kmust-why** [comment]
训练的是自己标注的灰度图像，这会是什么问题？

**Comment by lijianaiml** [comment]
原实现默认rgb三通道,可能是channel不匹配
